### ISSUE TITLE
"today" doesn't show up as editable field for psa_biomass, but we rely on it

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/etl-forms#18]
It's in multiple versions, but I specifically noticed that `vEchkcAone8S7y4eYhgru4` has a biomass form in `va_psa` that needs to be fixed, but what it's missing is the `today` field. But there's no way to edit it, given the list in the `editable_list_by_version` table.

**Comment by mikahpinegar** [comment]
resolved
