### ISSUE TITLE
Allow water sensor install forms with only one rep

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/etl-forms#39]
**Request**:
Allow a site that only has bare+cover for one rep to go through

**Problems I see**:
What happens when there is a second rep, but it was a failed scan? It will APPEAR to the parser as if the other rep is just missing. Example: kobo table uid 2083 (abridged):
```json
{
  "_id": 136870066,
  "formhub/uuid": "91a9837b0e8f4969849c1991330985d0",

  "group_vm21f92/form_name": "psa_water_sensor_install",
  "group_vm21f92/form_version": "v4",
  "farm_info_group/code": "BIG",

  "barcode_gateway": "21000171",
  "group_uv9yg82/cover_crop_node_rep1": "18000337",
  "group_uv9yg82/fail_scan_001": "alt_cover_crop_node_rep1",
  "group_uv9yg82/manual_type_cover_crop_node_rep1": "18000598",
  "group_uv9yg82/gps_cover_crop_node_rep1": "34.5441499 -79.2804115 48.88076400756836 5.0",
  "group_uv9yg82/bare_node_rep1": "18000598",
  "group_uv9yg82/fail_scan_002": "alt_bare_node_rep1",
  "group_uv9yg82/manual_type_barcode_gateway_001": "18000337",
  "group_uv9yg82/gps_bare_node_rep1": "34.5438269 -79.2804127 44.68724822998047 4.8",
  "group_uv9yg82/issues_rep1": "1800",
  "group_uv9yg82/cover_crop_node_rep2": "18000332",
  "group_uv9yg82/gps_cover_crop_node_rep2": "34.5435318 -79.2804177 38.889808654785156 4.571",
  "group_uv9yg82/bare_node_rep2": "18000346",
  "group_uv9yg82/gps_bare_node_rep2": "34.5432729 -79.2804502 43.56283950805664 5.0",
  "__version__": "vCK5tppVaNkkfWMhtddxEb",

}
```
Since this one has `fail_scan_002`, we need to go in and manually fix `"group_uv9yg82/bare_node_rep1"` to `18000337`. But if we were to drop any restrictions (like `not_null` on `bare_node_rep1`), it would get parsed through just fine, push a NULL to that cell (or omit the row entirely if neither was there), and not give the user/shepherd a chance to fix it.

**Possible workaround**: remove the not_null restriction, but have a test that scans the whole form before beginning looking for anything with "fail_scan" and kick the form when that happens. How feasible is that?

**Additional thoughts**:
Is it a problem to have mis-aligned scans, or rows with only bare or cover, not both, etc? It's harder for the humans to keep track of if they're looking at the table, but it won't break the API for finding the right rows in the sensor table. Also it means that the uninstall form parser will have to scan over everything 3 times, to find the appropriate row to mark `time_end` for each serial.

**Comment by brianwdavis** [comment]
@mikahpinegar this is the brain dump I was looking for today. I'm good with where we left it (requiring full rows, and letting rows that lack both cover and bare nodes fall away).

However, I think there are other forms where there might be a `"fail_scan_***"` field, and it would be a good last step to catch those in any corner cases we haven't considered. Any time there's a fail scan and manual entry, we want to make sure they fix that.

**Comment by mikahpinegar** [comment]
so wait, if any fail scan field is present we want to mark the form as invalid and have them fix it? or we want the logic to parse out all the fail scans and make a valid form?

**Comment by brianwdavis** [comment]
we want them to manually fix any fail scans

**Comment by mikahpinegar** [comment]
if any column has the string `fail` in it, fail the whole form
