### ISSUE TITLE
Extraneous column in water sensor install dict

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/etl-forms#5]
https://github.com/precision-sustainable-ag/etl-forms/blob/57393394a361e7bf331767d0a0b152acf2193996/psa_water_sensor_install/wsensor_install_vuiiHRr2MJSGzFwSncyLP9.py#L37-L38

I don't think this is correct. There shouldn't be anything in time_end for the install form

**Comment by mikahpinegar** [comment]
removed time end
